[package]
name = "cykusz-rust"
version = "0.1.0"
authors = ["Rafal Mielniczuk <rafalm3@gmail.com>"]

[lib]
name = "cykusz_rust"
crate-type = ["staticlib"]

[dependencies.core]
git = "https://github.com/rafalmiel/rust-libcore"

[dependencies.rlibc]
git = "https://github.com/rafalmiel/rlibc.git"

